################################################################
#
#
# Pipeline pipeline_piq.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

chunk_size: 6

PIQ_PATH: /shared/sudlab1/General/apps/bio/PIQ_human
piq_condaenv: alexia
